
sensor:
  - platform: homeassistant
    name: "Senzor teploty šatník z HA"
    entity_id: sensor.senzor_satnik_temperature
    #update_interval: 60s
    id: senzor_satnik_temperature

  - platform: homeassistant
    name: "Senzor teploty kúpelňa z HA"
    entity_id: sensor.senzor_kupelna_temperature
    id: senzor_kupelna_temperature

  - platform: homeassistant
    name: "Senzor teploty spálňa z HA"
    entity_id: sensor.senzor_spalna_temperature
    id: senzor_spalna_temperature

  - platform: homeassistant
    name: "Senzor teploty kuchyňa z HA"
    entity_id: sensor.senzor_kuchyna_temperature
    id: senzor_kuchyna_temperature
    
  - platform: homeassistant
    name: "Senzor teploty obývačka z HA"
    entity_id: sensor.senzor_obyvacka_2np_temperature
    id: senzor_obyvacka_2np_temperature

###### Other temperature sensor sample #######

  # - platform: dht
    # model : DHT22
    # pin: GPIO25
    # temperature:
      # name: "Switch Temperature"
      # id: switch_fan_controller_temperature
    # humidity:
      # name: "Switch Humidity"
      # id: switch_fan_controller_humidity
    # update_interval: 30s


    
  # - platform: xiaomi_lywsdcgq
    # mac_address: 58:2D:34:37:F1:10
    # temperature:
      # name: "Corridor Temperature"
      # id: xiaomi_corridor_temperature
    # humidity:
      # name: "Corridor Humidity"
      # id: xiaomi_corridor_humidity
    # battery_level:
      # name: "Corridor Xiaomi LYWSDCGQ Battery Level"
      # id: xiaomi_corridor_battery_level

      
# Connect 1-Wire bus with DS18B20 temperature sensors

# dallas:
  # - pin: GPI22
    # update_interval: 15s

# sensor:
  # - platform: dallas
    # address: 0x8b031760522cff28
    # name: "301_Heizkreis-WC-Vorlauf"
    # id: WC_Vorlauf
    # resolution: 12
    # accuracy_decimals: 2
    # filters:
      # - offset: 0.0

  # - platform: dallas
    # address: 0x353c38f649a51b28
    # name: "301_Heizkreis-WC-Ruecklauf"
    # id: WC_Ruecklauf
    # resolution: 12
    # accuracy_decimals: 2
    # filters:
      # - offset: 0.0
