
sensor:
  - platform: homeassistant
    name: "Mancave temperature sensor from hassio"
    entity_id: sensor.sensor_mancave_temperature
    #update_interval: 60s
    id: sensor_mancave_temperature

  - platform: homeassistant
    name: "Studio temperature sensor from hassio"
    entity_id: sensor.sensor_studio_temperature
    id: sensor_studio_temperature

  - platform: homeassistant
    name: "Bedroom temperature sensor from hassio"
    entity_id: sensor.sensor_bedroom_temperature
    id: sensor_bedroom_temperature

  - platform: homeassistant
    name: "Bathroom temperature sensor from hassio"
    entity_id: sensor.sensor_bathroom_temperature
    id: sensor_bathroom_temperature
    
  - platform: homeassistant
    name: "Femcave temperature sensor from hassio"
    entity_id: sensor.sensor_femcave_temperature
    id: sensor_femcave_temperature

###### Other temperature sensor sample #######

  # - platform: dht
    # model : DHT22
    # pin: GPIO25
    # temperature:
      # name: "Switch Temperature"
      # id: switch_fan_controller_temperature
    # humidity:
      # name: "Switch Humidity"
      # id: switch_fan_controller_humidity
    # update_interval: 30s


    
  # - platform: xiaomi_lywsdcgq
    # mac_address: 58:2D:34:37:F1:10
    # temperature:
      # name: "Corridor Temperature"
      # id: xiaomi_corridor_temperature
    # humidity:
      # name: "Corridor Humidity"
      # id: xiaomi_corridor_humidity
    # battery_level:
      # name: "Corridor Xiaomi LYWSDCGQ Battery Level"
      # id: xiaomi_corridor_battery_level

      
# Connect 1-Wire bus with DS18B20 temperature sensors

# dallas:
  # - pin: GPI22
    # update_interval: 15s

# sensor:
  # - platform: dallas
    # address: 0x8b031760522cff28
    # name: "301_Heizkreis-WC-Vorlauf"
    # id: WC_Vorlauf
    # resolution: 12
    # accuracy_decimals: 2
    # filters:
      # - offset: 0.0

  # - platform: dallas
    # address: 0x353c38f649a51b28
    # name: "301_Heizkreis-WC-Ruecklauf"
    # id: WC_Ruecklauf
    # resolution: 12
    # accuracy_decimals: 2
    # filters:
      # - offset: 0.0